const errorCodes = {
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    ADD_PRODUCT_ERROR: 'ADD_PRODUCT_ERROR',
    UPDATE_PRODUCT_ERROR: 'UPDATE_PRODUCT_ERROR',
    DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
  };
  
  module.exports = errorCodes;
  
  